--1
CREATE TABLE PERSON 
(
PERSON_ID VARCHAR2(40) NOT NULL CONSTRAINT PERSON_PK PRIMARY KEY,
FIRST_NAME VARCHAR2(25) NOT NULL,
LAST_NAME VARCHAR2(25) NOT NULL,
STREET_NO VARCHAR2(20),
ZIP_CODE VARCHAR2(20),
CITY VARCHAR2(20),
PASSWORD VARCHAR2(100) NOT NULL,
GENDER VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
RATING NUMBERNO_OF_PERSON_RATED NUMBER
);

--DROP TABLE PERSON;

--2
CREATE TABLE PERSON_NUMBER
(
PERSON_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
PHONE_NO VARCHAR2(15) NOT NULL
);

--DROP TABLE PERSON_NUMBER;

--3
CREATE TABLE DRIVER
(
DRIVER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
IMAGE VARCHAR2(150),
NID VARCHAR2(30) NOT NULL UNIQUE,
DRIVING_LICENSE VARCHAR2(40) NOT NULL UNIQUE
);

--DROP TABLE DRIVER;

--4
CREATE TABLE UBER_USER
(
UBER_USER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
HOME_LOCATION VARCHAR2(30),
WORK_LOCATION VARCHAR2(30),
CURRENT_LOCATION VARCHAR2(30)
);

--DROP TABLE UBER_USER;

--5
CREATE TABLE TRANSPORT
(
TRANS_ID VARCHAR2(40) CONSTRAINT TRANSPORT_PK PRIMARY KEY,
DRIVER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
BRAND VARCHAR2(20),
MODEL VARCHAR2(20) NOT NULL,
TRANS_LICENSE VARCHAR2(40) NOT NULL UNIQUE,
TRANS_TYPE VARCHAR2(20)
);

--DROP TABLE TRANSPORT;

--6
CREATE TABLE REQUEST
(
REQUEST_ID VARCHAR2(40) CONSTRAINT REQUEST_PK PRIMARY KEY,
TRANS_ID VARCHAR2(40) REFERENCES TRANSPORT(TRANS_ID) ON DELETE CASCADE,
DRIVER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
USER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

--DROP TABLE REQUEST;

--7
CREATE TABLE TRIP
(
TRIP_ID VARCHAR2(60) CONSTRAINT TRIP_PK PRIMARY KEY, 
START_TIME DATE DEFAULT SYSDATE,
END_TIME DATE DEFAULT SYSDATE,
EXPECTED_FARE NUMBER(6,2),
START_LOCATION VARCHAR2(100),
END_LOCATION VARCHAR2(100),
DRIVER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
USER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
REQUEST_ID VARCHAR2(40) REFERENCES REQUEST(REQUEST_ID) ON DELETE CASCADE,
PAYMENT_ID VARCHAR2(40) REFERENCES PAYMENT(PAYMENT_ID) ON DELETE CASCADE
);

--DROP TABLE TRIP;

--8
CREATE TABLE ACCIDENT
(
REPORT_ID VARCHAR2(40) CONSTRAINT ACCIDENT_PK PRIMARY KEY,
TRANS_ID VARCHAR2(40) REFERENCES TRANSPORT(TRANS_ID) ON DELETE CASCADE,
DRIVER_ID VARCHAR2(40) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
OCCUR_TIME DATE
);

--DROP TABLE ACCIDENT;

--9
CREATE TABLE PROMO
(
PROMO_CODE_NO VARCHAR2(40) CONSTRAINT PROMO_PK PRIMARY KEY,
DISCOUNT_PERCENTAGE NUMBER,
MAX_PROMO_AMOUNT NUMBER,
MAX_USE_PER_USER NUMBER,
PROMO_STATUS VARCHAR2(20),
ENROLLED_AT DATE,
EXPIRED_AT DATE
);

--DROP TABLE PROMO;

--10
CREATE TABLE PAYMENT
(
PAYMENT_ID VARCHAR2(40) CONSTRAINT PAYMENT_PK PRIMARY KEY,
NET_AMOUNT NUMBER,
PAYMENT_RATE NUMBER,
PROMO_CODE_ID VARCHAR2(40) REFERENCES PROMO(PROMO_CODE_NO) ON DELETE CASCADE
);

--DROP TABLE PAYMENT;

--11
CREATE TABLE LOCATION
(
PRIMARY KEY(LATTITUDE,LONGITUDE),
LATTITUDE NUMBER NOT NULL,
LONGITUDE NUMBER NOT NULL,
ADDRESS VARCHAR2(80)
);

--DROP TABLE LOCATION;

--12
CREATE TABLE SEES
(
LATTITUDE NUMBER NOT NULL,
LONGITUDE NUMBER NOT NULL,
PERSON_ID VARCHAR2(40) NOT NULL,
PRIMARY KEY(LATTITUDE,LONGITUDE,PERSON_ID),
FOREIGN KEY (LATTITUDE,LONGITUDE) REFERENCES LOCATION(LATTITUDE,LONGITUDE) ON DELETE CASCADE,
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

--DROP TABLE SEES;

--13
CREATE TABLE GETS
(
USER_ID VARCHAR2(40),
PROMO_CODE_NO_ID VARCHAR2(40),
PRIMARY KEY(USER_ID, PROMO_CODE_NO_ID),
FOREIGN KEY(USER_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
FOREIGN KEY(PROMO_CODE_NO_ID) REFERENCES PROMO(PROMO_CODE_NO) ON DELETE CASCADE
);

--DROP TABLE GETS;

--14
CREATE TABLE CHOOSE
(
USER_ID VARCHAR2(40),
TRANS_ID VARCHAR2(40),
--PRIMARY KEY(USER_ID, TRANS_ID),
FOREIGN KEY(USER_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
FOREIGN KEY(TRANS_ID) REFERENCES TRANSPORT(TRANS_ID) ON DELETE CASCADE
);

--DROP TABLE CHOOSE;
--ALTER TABLE LOCATION ADD ADDRESS VARCHAR2(80);
--ALTER TABLE TRIP MODIFY START_LOCATION VARCHAR2(100);
--ALTER TABLE TRIP MODIFY END_LOCATION VARCHAR2(100);
--ALTER TABLE PERSON MODIFY PASSWORD VARCHAR2(100);
--ALTER TABLE PERSON MODIFY EMAIL VARCHAR2(50);
ALTER TABLE PERSON ADD NO_OF_PERSON_RATED NUMBER;
